### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by ChervyachokMigo** [pmcrwf-mid/ZTE-MF79U-api#2]
2023-04-23 14:16:44.001 | DEBUG    | __main__:<module>:79 - Settings loaded
Traceback (most recent call last):
  File "h:\!stuff\ZTE modem firmware\api\ZTE-MF79U-api-main\main.py", line 80, in <module>
    cookies = auth(settings["password"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\!stuff\ZTE modem firmware\api\ZTE-MF79U-api-main\main.py", line 39, in auth
    raise Exception("Auth Error")
Exception: Auth Error

**Comment by fengjiaqi927** [comment]
it seems that you fail to login the ZTE-web. Have you customized your password in settings.json? If it still didn't work, you can try with shell scripts in my homepage: https://github.com/fengjiaqi927/ZTE-MF79U-shell-scripts
